## This configuration was generated by terraform-provider-oci

resource oci_core_internet_gateway export_internet-gateway {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:20.940Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "internet-gateway"
  enabled      = "true"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  vcn_id = oci_core_vcn.export_TF-VCN1.id
}

resource oci_core_internet_gateway export_internet-gateway_1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:20.940Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "internet-gateway"
  enabled      = "true"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  vcn_id = oci_core_vcn.export_TF-VCN1_1.id
}

resource oci_core_service_gateway export_service-gateway {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:20.923Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "service-gateway"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.iad.aaaaaaaam4zfmy2rjue6fmglumm3czgisxzrnvrwqeodtztg7hwa272mlfna"
  }
  vcn_id = oci_core_vcn.export_TF-VCN1.id
}

resource oci_core_service_gateway export_service-gateway_1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:20.923Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "service-gateway"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.iad.aaaaaaaam4zfmy2rjue6fmglumm3czgisxzrnvrwqeodtztg7hwa272mlfna"
  }
  vcn_id = oci_core_vcn.export_TF-VCN1_1.id
}

resource oci_core_subnet export_Subnet-2 {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.120.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T22:15:01.688Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  dhcp_options_id = oci_core_vcn.export_TF-VCN1.default_dhcp_options_id
  display_name    = "Subnet-2"
  dns_label       = "subnet2"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_TF-VCN1.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_TF-VCN1.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_TF-VCN1.id
}

resource oci_core_subnet export_Subnet-1 {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.110.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T21:57:46.912Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  dhcp_options_id = oci_core_vcn.export_TF-VCN1.default_dhcp_options_id
  display_name    = "Subnet-1"
  dns_label       = "subnet1"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_TF-VCN1.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_TF-VCN1.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_TF-VCN1.id
}

resource oci_core_subnet export_Subnet-1_1 {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.110.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T21:57:46.912Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  dhcp_options_id = oci_core_vcn.export_TF-VCN1_1.default_dhcp_options_id
  display_name    = "Subnet-1"
  dns_label       = "subnet1"
  freeform_tags = {
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_TF-VCN1_1.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_TF-VCN1_1.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_TF-VCN1_1.id
}

resource oci_core_vcn export_TF-VCN1 {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:19.365Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "TF-VCN1"
  dns_label    = "tfvcnmodule"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_vcn export_TF-VCN1_1 {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:19.365Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "TF-VCN1"
  dns_label    = "tfvcnmodule"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-TF-VCN1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:19.365Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name     = "Default DHCP Options for TF-VCN1"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  manage_default_resource_id = oci_core_vcn.export_TF-VCN1.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "tfvcnmodule.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_route_table export_internet-route {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:21.971Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "internet-route"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  route_rules {
    description       = "Terraformed - Auto-generated at Internet Gateway creation: Internet Gateway as default gateway"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_internet-gateway.id
  }
  vcn_id = oci_core_vcn.export_TF-VCN1.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-TF-VCN1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:19.365Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "Default Route Table for TF-VCN1"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  manage_default_resource_id = oci_core_vcn.export_TF-VCN1.default_route_table_id
}

resource oci_core_default_security_list export_Default-Security-List-for-TF-VCN1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:19.365Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "Default Security List for TF-VCN1"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  manage_default_resource_id = oci_core_vcn.export_TF-VCN1.default_security_list_id
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-TF-VCN1_1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:19.365Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name     = "Default DHCP Options for TF-VCN1"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  manage_default_resource_id = oci_core_vcn.export_TF-VCN1_1.default_dhcp_options_id
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "tfvcnmodule.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_nat_gateway export_nat-gateway {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:20.511Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "nat-gateway"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  public_ip_id = "ocid1.publicip.oc1.iad.aaaaaaaah7rvg2r5bynuqrfywaxaihweslidt6kk63davz43npspupgjgm2a"
  vcn_id       = oci_core_vcn.export_TF-VCN1_1.id
}

resource oci_core_route_table export_nat-route {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:23.318Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "nat-route"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  route_rules {
    description       = "Terraformed - Auto-generated at NAT Gateway creation: NAT Gateway as default gateway"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_nat-gateway.id
  }
  route_rules {
    description       = "Terraformed - Auto-generated at Service Gateway creation: All Services in region to Service Gateway"
    destination       = "all-iad-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_service-gateway_1.id
  }
  vcn_id = oci_core_vcn.export_TF-VCN1_1.id
}

resource oci_core_route_table export_internet-route_1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:21.971Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "internet-route"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  route_rules {
    description       = "Terraformed - Auto-generated at Internet Gateway creation: Internet Gateway as default gateway"
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_internet-gateway_1.id
  }
  vcn_id = oci_core_vcn.export_TF-VCN1_1.id
}

resource oci_core_default_route_table export_Default-Route-Table-for-TF-VCN1_1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:19.365Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "Default Route Table for TF-VCN1"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  manage_default_resource_id = oci_core_vcn.export_TF-VCN1_1.default_route_table_id
}

resource oci_core_default_security_list export_Default-Security-List-for-TF-VCN1_1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "TagDefaults.Created_at" = "2022-07-20T18:40:19.365Z"
    "TagDefaults.Created_by" = "oracleidentitycloudservice/chris.iorg@oracle.com"
  }
  display_name = "Default Security List for TF-VCN1"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  manage_default_resource_id = oci_core_vcn.export_TF-VCN1_1.default_security_list_id
}

